name: mob_monitoring
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: any
  google_maps_flutter: any
  location: any
  intl: any 
  geocoding: any
  geolocator: any
  http: any
  flutter_speed_dial: any
  iconsax: ^0.0.8
  dio: any
  flutter_polyline_points: any
  video_player: any
  chewie: any
  logger: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
